name: dictionary_api
description: A Flutter Project for calling dictionary_api
publish_to: "none"
version: 1.0.1+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # http: ^0.13.5
  # url_strategy: ^0.2.0
  dio: ^5.0.3
  provider: ^6.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  meta: ^1.9.1

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
